ALTER TABLE "Inventory" ALTER COLUMN "onHand" TYPE DOUBLE PRECISION, ALTER COLUMN "reserved" TYPE DOUBLE PRECISION, ALTER COLUMN "minStock" TYPE DOUBLE PRECISION;
ALTER TABLE "StockMovement" ALTER COLUMN "quantity" TYPE DOUBLE PRECISION, ALTER COLUMN "onHandAfter" TYPE DOUBLE PRECISION, ALTER COLUMN "reservedAfter" TYPE DOUBLE PRECISION;
